fix(compile): use temporary file for `--load`
On Emacs 29.1 some weird bug, not available before and after, causes issues
when using on demand created file via process substitution.

```
Error: error ("Maximum buffer size exceeded")
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x1d4e59f1b5aef77d>))
  debug-early-backtrace()
  debug-early(error (error "Maximum buffer size exceeded"))
  insert-file-contents("/dev/fd/63")
  load-with-code-conversion("/dev/fd/63" "/dev/fd/63" nil t)
  load("/dev/fd/63" nil t)
  command-line-1(("--directory" "." "--load" "/dev/fd/63" "--eval" "(unless (byte-compile-file \".emacs\") (kill-emacs 1))"))
  command-line()
  normal-top-level()
Maximum buffer size exceeded
```